### ISSUE TITLE
Should full_name_d be further cleaned up?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1165]
While loading test Marc records into a local Muscat instance, I've come across several cases that have me thought that maybe further cleaning may be useful.  Marc (sub)fields often end with punctuation, for example:

https://catalog.loc.gov/vwebv/staffView?bibId=1623186

```
1001_ |a Kaczyński, Tadeusz.
24510 |a Lutosławski / |c Tadeusz Kaczyński.
260__ |a Warszawa : |b Sutkowski Edition Warsaw, |c [1994?]-
300__ |a v. <1 > : |b ill., ports. ; |c 25 cm.
440_0 |a Historia muzyki polskiej ; |v t. 9
504__ |a Includes bibliographical references (v. 1, p. [243]) and indexes.
5051_ |a Życie i muzyka
60010 |a Lutosławski, Witold, |d 1913-1994. 
```

Loading records like that into Muscat would create names like that as full_name_d:

```
kaczyński, tadeusz.
lutosławski, witold,
```

Which brings an obvious improvement to remove final punctuation.  But also, maybe the cleaned up versions should remove diacritics, as it is costumary, for those using Latin alphabet, to consider them equivalent (furthermore, as not everybody has had an adequate keyboard when the name was typed).  This is easily done with I18n.transliterate (https://www.rubydoc.info/gems/activesupport/2.3.17/I18n.transliterate), but as noted, only works with Latin alphabets.

That would bring https://github.com/rism-digital/muscat/blob/develop/lib/marc_person.rb get_full_name_and_dates to be something like:

```diff
diff --git a/lib/marc_person.rb b/lib/marc_person.rb
index 586844c..4c0db9a 100644
--- a/lib/marc_person.rb
+++ b/lib/marc_person.rb
@@ -10,40 +10,41 @@ class MarcPerson < Marc

     if node = first_occurance("100", "a")
       if node.content
-        full_name = node.content.truncate(128)
-        full_name_d = node.content.downcase.truncate(128)
+        full_name = node.content.truncate(128).sub(/[ ,\.]+$/, '')
+        full_name_d = I18n.transliterate(full_name.downcase)
+        full_name_d = full_name.downcase if full_name_d.include? '???'
       end
     end
```

```ruby
names = ["Bartók, Béla", "Martinů, Bohuslav", "Lutosławski, Witold", 
         "Schönberg, Arnold", "Schoenberg, Arnold", "Шостако́вич, Дми́трий Дми́триевич"]
names.each { |name| puts "#{name} -> #{name.downcase} => #{I18n.transliterate(name.downcase)}" }
```

With non-latin alphabets, like Cyrillic, we revert it to downcase, as I haven't found an easy alternative:

```
Bartók, Béla -> bartók, béla => bartok, bela
Martinů, Bohuslav -> martinů, bohuslav => martinu, bohuslav
Lutosławski, Witold -> lutosławski, witold => lutoslawski, witold
Schönberg, Arnold -> schönberg, arnold => schonberg, arnold
Schoenberg, Arnold -> schoenberg, arnold => schoenberg, arnold
Шостако́вич, Дми́трий Дми́триевич -> шостако́вич, дми́трий дми́триевич => ???????????, ???????? ???????????
```

It is not perfect (like the Schoenberg ~ Schönberg case), but I think that it would be better than the current transformation.  Moreover, if it can be used for sorting, as in this moment names starting with a letter with a diacritic go at the end of the list.

Would you accept a PR like that?

**Comment by fjorba** [comment]
As a matter of fact, the documentation states that the diacritics should effectively be removed:

https://github.com/rism-digital/muscat/blob/develop/app/models/person.rb#L6

```
# === Fields
# * <tt>full_name</tt> - Full name of the person: Second name, Name
# * <tt>full_name_d</tt> - Downcase with UTF chars stripped 
# * <tt>life_dates</tt> - Dates in the form xxxx-xxxx
```

**Comment by fjorba** [comment]
As a matter of fact, the documentation states that the diacritics should effectively be removed:

https://github.com/rism-digital/muscat/blob/develop/app/models/person.rb#L6

```
# === Fields
# * <tt>full_name</tt> - Full name of the person: Second name, Name
# * <tt>full_name_d</tt> - Downcase with UTF chars stripped 
# * <tt>life_dates</tt> - Dates in the form xxxx-xxxx
```

**Comment by xhero** [comment]
I think there are two issues here:
1) Pucntuation, do we also have it in RISM data? I'm not a fan of changing data on the fly, as the data should be imported correctly, not subtly changed in the system. So ending punctuation should be stripped at the import level.
2) full_name_d, we can fix it, but all the search is done via Solr, and I think it would be better to improve indexing there where proper collation an be done, there was already some work done by @fjorba and @ahankinson that I merged, I'm not sure if it is enough.
Speaking of _d fields, probably we could drop them altogether, they are a residuate from the days pre solr.

**Comment by fjorba** [comment]
I see.  Stripping punctuation would be only for the _d authority field, not for the incoming bibliographic record. And while I understand that if searching is done via Solr, it may still be necessary for sorting, as @jenniferward was interested in.  I still don't know if it is possible to sort ignoring capitalisation and diacritics.

**Comment by fjorba** [comment]
As I see that currently the alphabetic order, at least for personal names, works well, that is, ignoring diacritics, I close this issue.
